spring.application.name=attendance

spring.datasource.url=jdbc:mysql://localhost:3306/attendance_management_system
spring.datasource.username=root
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true

app-jwt-secret=uj6sh3j5n5j90djj1gje90knd8sh8fg9s08gjs78j1nc0187ehb4js4aoj48jss
app-expiration-milliseconds=86400000
